name: Superbook
version: @version@
main: com.drazisil.superbook.SuperBook
api-version: "1.13"
authors: [Drazisil]
description: Create a rulebook, run commands when players agree
permissions:
  superbook.agree:
    description: Allow a player to agree to a book
    default: true
  superbook.give.*:
    description: Wildcard give permission
    default: op
    children:
      superbook.give.others: true
      superbook.give.self: true
  superbook.give.others:
    description: Allows a player to give others a book
    default: op
  superbook.give.self:
    description: Allows a player to give themself a book
    default: op

commands:
  superbook:
    description: Superbook management
    aliases:
      - sbook
    usage: |
      /superbook agree <book_key> <approval_code>
      /superbook give <book_key> [count]
      /superbook give <player> <book_key> [count]
      /superbook list
  superbook agree:
    description: Agree to the book, using the book's approval code.
    aliases:
      - agree
    usage: /agree <book name> <password>
  superbook give:
    description: Give a player (yourself if not specified) a book by it's key. Count is optional.
    usage: |
      /superbook give <book_key> [count]
      /superbook give <player> <book_key> [count]

